// ═══════════════════════════════════════════
// MITM PlacePro — Constants & Mock Data
// ═══════════════════════════════════════════

export const DEPARTMENTS = [
  "CSE",
  "ISE",
  "ECE",
  "EEE",
  "MECH",
  "CIVIL",
  "AIML",
  "AIDS",
  "MBA",
  "MCA",
] as const;

export const SECTORS = [
  "Information Technology",
  "Finance & Banking",
  "Manufacturing",
  "Healthcare",
  "Consulting",
  "E-Commerce",
  "Automotive",
  "Telecom",
  "Education",
  "Energy",
  "Real Estate",
  "Media & Entertainment",
  "Other",
] as const;

export const ROUND_TYPES = [
  { value: "written", label: "Written / Aptitude" },
  { value: "technical", label: "Technical Round" },
  { value: "HR", label: "HR Round" },
  { value: "GD", label: "Group Discussion" },
  { value: "coding", label: "Coding Round" },
] as const;

export const WORK_MODES = [
  { value: "on-site", label: "On-Site" },
  { value: "remote", label: "Remote" },
  { value: "hybrid", label: "Hybrid" },
] as const;

export const TURNOVER_RANGES = [
  "< 1 Cr",
  "1 - 10 Cr",
  "10 - 100 Cr",
  "100 - 500 Cr",
  "500 Cr+",
] as const;

export const CATEGORIES = ["General", "OBC", "SC", "ST", "EWS"] as const;

export const GENDERS = ["Male", "Female", "Prefer not to say"] as const;

export const BOARDS = [
  "CBSE",
  "ICSE",
  "Karnataka State Board",
  "Maharashtra State Board",
  "Other State Board",
] as const;

export const STREAMS = ["Science", "Commerce", "Arts"] as const;

export const PROFICIENCY_LEVELS = [
  "Basic",
  "Conversational",
  "Fluent",
  "Native",
] as const;

// ═══════════════ MOCK DATA ═══════════════

export const MOCK_STUDENTS = [
  {
    id: "s1",
    userId: "u1",
    usn: "4MT21CS001",
    fullName: "Arjun Sharma",
    phone: "+919876543210",
    department: "CSE",
    cgpa: 8.75,
    tenthPercent: 92.5,
    twelfthPercent: 88.0,
    backlogs: 0,
    profileComplete: true,
    placementStatus: "placed" as const,
    photoUrl: "",
    email: "arjun.sharma@mitm.edu.in",
    semester: 8,
    profileData: { skills: ["React", "Node.js", "Python", "SQL"], headline: "Final Year CSE Student" },
  },
  {
    id: "s2",
    userId: "u2",
    usn: "4MT21CS002",
    fullName: "Priya Patel",
    phone: "+919876543211",
    department: "CSE",
    cgpa: 9.12,
    tenthPercent: 95.0,
    twelfthPercent: 91.5,
    backlogs: 0,
    profileComplete: true,
    placementStatus: "interview_scheduled" as const,
    photoUrl: "",
    email: "priya.patel@mitm.edu.in",
    semester: 8,
    profileData: { skills: ["Java", "Spring Boot", "AWS", "Docker"], headline: "Aspiring Backend Engineer" },
  },
  {
    id: "s3",
    userId: "u3",
    usn: "4MT21EC003",
    fullName: "Rahul Kumar",
    phone: "+919876543212",
    department: "ECE",
    cgpa: 7.85,
    tenthPercent: 85.0,
    twelfthPercent: 79.5,
    backlogs: 1,
    profileComplete: true,
    placementStatus: "shortlisted" as const,
    photoUrl: "",
    email: "rahul.kumar@mitm.edu.in",
    semester: 8,
    profileData: { skills: ["VLSI", "Embedded C", "MATLAB", "PCB Design"], headline: "ECE Student | Embedded Systems" },
  },
  {
    id: "s4",
    userId: "u4",
    usn: "4MT21IS004",
    fullName: "Sneha Reddy",
    phone: "+919876543213",
    department: "ISE",
    cgpa: 8.45,
    tenthPercent: 89.0,
    twelfthPercent: 84.0,
    backlogs: 0,
    profileComplete: true,
    placementStatus: "offered" as const,
    photoUrl: "",
    email: "sneha.reddy@mitm.edu.in",
    semester: 8,
    profileData: { skills: ["React", "TypeScript", "GraphQL", "MongoDB"], headline: "Full Stack Developer" },
  },
  {
    id: "s5",
    userId: "u5",
    usn: "4MT21ME005",
    fullName: "Vikram Singh",
    phone: "+919876543214",
    department: "MECH",
    cgpa: 7.20,
    tenthPercent: 78.0,
    twelfthPercent: 72.5,
    backlogs: 0,
    profileComplete: false,
    placementStatus: "none" as const,
    photoUrl: "",
    email: "vikram.singh@mitm.edu.in",
    semester: 8,
    profileData: { skills: ["AutoCAD", "SolidWorks"], headline: "" },
  },
  {
    id: "s6",
    userId: "u6",
    usn: "4MT21CS006",
    fullName: "Ananya Iyer",
    phone: "+919876543215",
    department: "CSE",
    cgpa: 9.45,
    tenthPercent: 96.5,
    twelfthPercent: 93.0,
    backlogs: 0,
    profileComplete: true,
    placementStatus: "placed" as const,
    photoUrl: "",
    email: "ananya.iyer@mitm.edu.in",
    semester: 8,
    profileData: { skills: ["ML", "Deep Learning", "Python", "TensorFlow", "Research"], headline: "AI/ML Enthusiast" },
  },
];

export const MOCK_COMPANIES = [
  {
    id: "c1",
    userId: "cu1",
    name: "Infosys Technologies",
    sector: "Information Technology",
    hqCity: "Bengaluru",
    website: "https://infosys.com",
    profileComplete: true,
    isActive: true,
    email: "hr@infosys.com",
    hrName: "Meera Joshi",
    description: "Global leader in next-generation digital services and consulting.",
    logoUrl: "",
  },
  {
    id: "c2",
    userId: "cu2",
    name: "Wipro Limited",
    sector: "Information Technology",
    hqCity: "Bengaluru",
    website: "https://wipro.com",
    profileComplete: true,
    isActive: true,
    email: "campus@wipro.com",
    hrName: "Rohit Verma",
    description: "Leading global IT, consulting, and business process services company.",
    logoUrl: "",
  },
  {
    id: "c3",
    userId: "cu3",
    name: "TCS",
    sector: "Information Technology",
    hqCity: "Mumbai",
    website: "https://tcs.com",
    profileComplete: true,
    isActive: true,
    email: "recruitment@tcs.com",
    hrName: "Kavya Nair",
    description: "India's largest IT services company and a global technology leader.",
    logoUrl: "",
  },
  {
    id: "c4",
    userId: "cu4",
    name: "Bosch India",
    sector: "Manufacturing",
    hqCity: "Bengaluru",
    website: "https://bosch.in",
    profileComplete: false,
    isActive: true,
    email: "careers@bosch.in",
    hrName: "Anil Patil",
    description: "Leading supplier of technology and services in automotive and industrial sectors.",
    logoUrl: "",
  },
];

export const MOCK_JOBS = [
  {
    id: "j1",
    companyId: "c1",
    title: "Software Engineer",
    ctcMinLpa: 4.5,
    ctcMaxLpa: 6.0,
    totalVacancies: 25,
    numRounds: 3,
    status: "open" as const,
    requiredSkills: ["Java", "SQL", "Problem Solving"],
    allowedDepartments: ["CSE", "ISE", "ECE"],
    minCgpa: 7.0,
    timePerCandidateMin: 30,
    roundsConfig: [
      { round: 1, name: "Aptitude Test", type: "written" as const },
      { round: 2, name: "Technical Interview", type: "technical" as const },
      { round: 3, name: "HR Interview", type: "HR" as const },
    ],
  },
  {
    id: "j2",
    companyId: "c2",
    title: "Project Engineer",
    ctcMinLpa: 3.8,
    ctcMaxLpa: 5.5,
    totalVacancies: 30,
    numRounds: 2,
    status: "open" as const,
    requiredSkills: ["Python", "Communication", "Teamwork"],
    allowedDepartments: ["CSE", "ISE", "ECE", "EEE"],
    minCgpa: 6.5,
    timePerCandidateMin: 25,
    roundsConfig: [
      { round: 1, name: "Online Assessment", type: "coding" as const },
      { round: 2, name: "Technical + HR", type: "technical" as const },
    ],
  },
  {
    id: "j3",
    companyId: "c3",
    title: "Systems Engineer",
    ctcMinLpa: 3.6,
    ctcMaxLpa: 7.0,
    totalVacancies: 50,
    numRounds: 4,
    status: "open" as const,
    requiredSkills: ["Java", "C++", "DBMS", "Networking"],
    allowedDepartments: ["CSE", "ISE", "ECE", "MECH"],
    minCgpa: 6.0,
    timePerCandidateMin: 20,
    roundsConfig: [
      { round: 1, name: "Aptitude + Verbal", type: "written" as const },
      { round: 2, name: "Coding Round", type: "coding" as const },
      { round: 3, name: "Technical", type: "technical" as const },
      { round: 4, name: "HR", type: "HR" as const },
    ],
  },
];

export const MOCK_DASHBOARD_STATS = {
  totalStudents: 1847,
  totalCompanies: 42,
  totalPlaced: 892,
  totalShortlisted: 1245,
  avgCtc: 5.8,
  profileCompletionRate: 78.5,
  placementRate: 48.3,
  departmentStats: [
    { department: "CSE", total: 480, placed: 312, percentage: 65.0 },
    { department: "ISE", total: 360, placed: 198, percentage: 55.0 },
    { department: "ECE", total: 300, placed: 156, percentage: 52.0 },
    { department: "EEE", total: 180, placed: 72, percentage: 40.0 },
    { department: "MECH", total: 240, placed: 84, percentage: 35.0 },
    { department: "CIVIL", total: 120, placed: 36, percentage: 30.0 },
    { department: "AIML", total: 90, placed: 22, percentage: 24.4 },
    { department: "AIDS", total: 77, placed: 12, percentage: 15.6 },
  ],
  companyStats: [
    { company: "TCS", placed: 156, avgCtc: 4.2 },
    { company: "Infosys", placed: 124, avgCtc: 5.5 },
    { company: "Wipro", placed: 98, avgCtc: 4.8 },
    { company: "Bosch", placed: 45, avgCtc: 7.2 },
    { company: "HCL Tech", placed: 67, avgCtc: 4.5 },
    { company: "Cognizant", placed: 89, avgCtc: 4.0 },
  ],
  monthlyTrend: [
    { month: "Oct", placements: 45, offers: 68 },
    { month: "Nov", placements: 124, offers: 156 },
    { month: "Dec", placements: 198, offers: 230 },
    { month: "Jan", placements: 267, offers: 312 },
    { month: "Feb", placements: 198, offers: 245 },
    { month: "Mar", placements: 60, offers: 78 },
  ],
};

export const MOCK_NOTIFICATIONS = [
  {
    id: "n1",
    userId: "u1",
    type: "shortlisted",
    title: "New Shortlist: Infosys",
    body: "45 students have been shortlisted for Software Engineer at Infosys.",
    metadata: {},
    isRead: false,
    createdAt: "2026-05-16T10:30:00Z",
  },
  {
    id: "n2",
    userId: "u1",
    type: "slot_assigned",
    title: "Slots Generated: TCS",
    body: "Interview slots have been allocated for 120 students at TCS.",
    metadata: {},
    isRead: false,
    createdAt: "2026-05-16T09:15:00Z",
  },
  {
    id: "n3",
    userId: "u1",
    type: "offer_letter",
    title: "Offer Letter Uploaded",
    body: "Bosch has uploaded offer letters for 12 placed students.",
    metadata: {},
    isRead: true,
    createdAt: "2026-05-15T16:45:00Z",
  },
  {
    id: "n4",
    userId: "u1",
    type: "round_result",
    title: "Round 1 Results: Wipro",
    body: "Wipro has submitted Round 1 results. 78 out of 120 students selected.",
    metadata: {},
    isRead: true,
    createdAt: "2026-05-15T14:00:00Z",
  },
];

export const SKILL_SUGGESTIONS = [
  "JavaScript", "TypeScript", "Python", "Java", "C++", "C", "Go", "Rust",
  "React", "Angular", "Vue.js", "Next.js", "Node.js", "Express.js", "NestJS",
  "Spring Boot", "Django", "Flask", "FastAPI", "Ruby on Rails",
  "HTML", "CSS", "Tailwind CSS", "SASS", "Bootstrap",
  "PostgreSQL", "MySQL", "MongoDB", "Redis", "Elasticsearch",
  "AWS", "Azure", "GCP", "Docker", "Kubernetes",
  "Git", "CI/CD", "Jenkins", "GitHub Actions",
  "Machine Learning", "Deep Learning", "NLP", "Computer Vision",
  "TensorFlow", "PyTorch", "Scikit-learn", "Pandas", "NumPy",
  "SQL", "NoSQL", "GraphQL", "REST API", "gRPC",
  "Data Structures", "Algorithms", "System Design",
  "Linux", "Networking", "Cybersecurity",
  "Figma", "UI/UX Design", "Adobe XD",
  "Communication", "Leadership", "Teamwork", "Problem Solving",
  "MATLAB", "VLSI", "Embedded C", "Arduino", "IoT",
  "AutoCAD", "SolidWorks", "CATIA", "3D Printing",
];
